---
version: "2"
use_cases:
- name: ($> .stack_usecase <$)
  sections:
  - name: Storage Account
    groups:
    - name: Azure Access Configuration
      technologies: [pipeline]
      vars:
      - name: "Azure Subscription ID"
        description: "The azure subscription id used to deploy the infrastructure."
        key: azure_subscription_id
        widget: cy_cred
        widget_config:
          cred_types:
            - azure
        type: string
        required: true
      - name: "Azure Tenant ID"
        description: "The azure tenant id used to deploy the infrastructure."
        key: azure_tenant_id
        widget: cy_cred
        widget_config:
          cred_types:
            - azure
        type: string
        required: true
      - name: "Azure Client ID"
        description: "The azure client id used to deploy the infrastructure."
        key: azure_client_id
        widget: cy_cred
        widget_config:
          cred_types:
            - azure
        type: string
        required: true
      - name: "Azure Client Secret"
        description: "The azure client secret used to deploy the infrastructure."
        key: azure_client_secret
        widget: cy_cred
        widget_config:
          cred_types:
            - azure
        type: string
        required: true
    - name: Azure Infrastructure
      technologies: [pipeline]
      vars:
      - name: "Resource Group Name"
        description: "The name of the resource group to create."
        key: rg_name
        widget: simple_text
        type: string
        default: ""
        validations: 
        - regexp: "^[0-9a-zA-Z_\\-\\.]{1,90}$" 
          error_message: "1 to 90 alphanumerics, underscores, hyphens, periods chars."
        required: true
      - name: "Storage Account Name"
        description: "The name of the storage account to create."
        key: sa_name
        widget: simple_text
        type: string
        default: ""
        validations: 
        - regexp: "^[0-9a-z]{3,24}$" 
          error_message: "3 to 24 numbers and lower-case letters chars."
        required: true
    - name: Pulumi Settings
      technologies: [pipeline]
      vars:
      # - name: "Pulumi Project"
      #   description: "The Pulumi project name."
      #   key: pulumi_project
      #   widget: simple_text
      #   type: string
      #   default: "storage-account"
      #   required: true
      - name: "Pulumi Stack"
        description: "The Pulumi stack name."
        key: pulumi_stack
        widget: simple_text
        type: string
        default: "dev"
        required: true
      - name: "Pulumi Access Token"
        description: "The Pulumi Cloud access token."
        key: pulumi_token
        type: string
        widget: cy_cred
        widget_config:
          cred_types:
            - custom
        default: ((pulumi.token))
        required: true
