---
# Configuration of the Cycloid stack
version: '2'
name: 'Terraform + Ansible template'
canonical: 'template-nexus-repository'
description: Deploys a Nexus Repository on an AWS, Azure or GCP instance using Terraform and Ansible.
author: '{{ stack_author }}'
image: 'https://cycloid-demo-stacks-logo.s3.eu-west-1.amazonaws.com/ansible.png'
status: 'private'
template: true
keywords:
- terraform
- ansible
- nexus
- '{{ stack_usecase }}'
technologies:
- technology: terraform
  version: 1.3.9
- technology: ansible
  version: 2.9

config:
  aws:
    name: 'AWS'
    description: 'Deploys a Nexus Repository in a single AWS instance'
    cloud_provider: aws
    # Pipeline and variable configuration for the AWS CD pipeline use case
    pipeline:
      pipeline:
        path: 'pipeline/pipeline.yml'
      variables:
        path: 'pipeline/variables.sample.yml'
        destination: '($ project $)/pipeline/($ environment $)/variables.yml'
    # Configuration of ansible for provisionning
    ansible:
      nexus:
        path: 'ansible/environments/nexus.yml.sample'
        destination: '($ project $)/ansible/environments/($ environment $)-nexus.yml'
    # Configuration of terraform (leave .sample extension to prevent terraform executing the sample file)
    terraform:
      main:
        path: 'terraform/aws/main.tf'
        destination: '($ project $)/terraform/aws/($ environment $)/main.tf'

  azure:
    name: 'Azure'
    description: 'Deploys a Nexus Repository in a single Azure instance'
    cloud_provider: azurerm
    # Pipeline and variable configuration for the Azure CD pipeline use case
    pipeline:
      pipeline:
        path: 'pipeline/pipeline.yml'
      variables:
        path: 'pipeline/variables.sample.yml'
        destination: '($ project $)/pipeline/($ environment $)/variables.yml'
    # Configuration of ansible for provisionning
    ansible:
      nexus:
        path: 'ansible/environments/nexus.yml.sample'
        destination: '($ project $)/ansible/environments/($ environment $)-nexus.yml'
    # Configuration of terraform
    terraform:
      main:
        path: 'terraform/azure/main.tf'
        destination: '($ project $)/terraform/azure/($ environment $)/main.tf'

  gcp:
    name: 'GCP'
    description: 'Deploys a Nexus Repository in a single GCP instance'
    cloud_provider: google
    # Pipeline and variable configuration for the GCP CD pipeline use case
    pipeline:
      pipeline:
        path: 'pipeline/pipeline.yml'
      variables:
        path: 'pipeline/variables.sample.yml'
        destination: '($ project $)/pipeline/($ environment $)/variables.yml'
    # Configuration of ansible for provisionning
    ansible:
      nexus:
        path: 'ansible/environments/nexus.yml.sample'
        destination: '($ project $)/ansible/environments/($ environment $)-nexus.yml'
    # Configuration of terraform
    terraform:
      main:
        path: 'terraform/gcp/main.tf'
        destination: '($ project $)/terraform/gcp/($ environment $)/main.tf'
