---
version: "2"
use_cases:
- name: '{{ stack_usecase }}'
  sections:
  - name: Nexus Repository
    groups:
    - name: Virtual machine specifications
      technologies: [terraform]
      vars:
{%- if stack_usecase == "aws" %}
      - name: "Instance type"
        description: "Instance type for the VM."
        key: vm_instance_type
        widget: slider_list
        type: string
        default: "t3a.medium"
        values:
            - "t3a.medium"
            - "t3a.large"
            - "t3a.xlarge"
        required: true
{%- elif stack_usecase == "azure" %}
      - name: "Instance type"
        description: "Instance type for the VM."
        key: vm_instance_type
        widget: slider_list
        type: string
        default: "Standard_DS2_v2"
        values:
            - "Standard_DS1_v2"
            - "Standard_DS2_v2"
            - "Standard_DS3_v2"
        required: true
{%- elif stack_usecase == "gcp" %}
      - name: "Machine type"
        description: "Machine type for the VM."
        key: vm_machine_type
        widget: slider_list
        type: string
        default: "n2-standard-2"
        values:
            - e2-medium
            - n2-standard-2
            - n2d-standard-2
        required: true
{%- endif %}
      - name: "Disk size"
        unit: Go
        description: "Disk size for the Nexus Repository."
        key: vm_disk_size
        widget: slider_range
        type: integer
        default: 30
        values:
            - 30
            - 250
        required: true
    - name: SSH Keypair for new instances
      technologies: [pipeline]
      vars:
      - name: "SSH Public key"
        description: "The public SSH key to connect via SSH to execute the Ansible playbook"
        key: keypair_public
        widget: cy_cred
        type: string
        default: ((keypair.ssh_pub))
        required: true
      - name: "SSH Private key"
        description: "The private SSH key to connect via SSH to execute the Ansible playbook"
        key: keypair_private
        widget: cy_cred
        type: string
        default: ((keypair.ssh_prv))
        required: true
    - name: Application Configuration
      technologies: [terraform]
      vars:
      - name: "Port"
        description: "Port where Nexus Repository service is exposed."
        key: nexus_port
        widget: simple_text
        type: string
        default: "8081"
        required: true
      - name: "Admin password"
        description: "Initial admin password for Nexus Repository first installation."
        key: nexus_admin_password
        widget: simple_text
        type: string
        default: "changeme"
        required: true

{%- if stack_usecase == "aws" %}
  - name: AWS Cloud Provider
    groups:
    - name: Access Configuration
      technologies: [pipeline]
      vars:
      - name: "AWS account"
        description: "The AWS account where to deploy the infrastructure. It contains access key and secret key."
        key: aws_cred
        widget: cy_cred
        widget_config:
          display_keys: false
          cred_types:
            - aws
        type: string
        default: "((aws))"
        required: true
      - name: "Amazon AWS region"
        description: "Amazon AWS region to use for Terraform."
        key: aws_region
        widget: auto_complete
        type: string
        values: ["eu-north-1","ap-south-1","eu-west-3","eu-west-2","eu-west-1","ap-northeast-2","ap-northeast-1","sa-east-1","ca-central-1","ap-southeast-1","ap-southeast-2","eu-central-1","us-east-1","us-east-2","us-west-1","us-west-2"]
        default: eu-west-1
        required: true
{%- elif stack_usecase == "azure" %}
  - name: Azure Cloud Provider
    groups:
    - name: Access Configuration
      technologies: [pipeline]
      vars:
      - name: "Azure credentials"
        description: "The azure credential used to deploy the infrastructure. It contains subscription_id, tenant_id, client_id, and client_secret."
        key: azure_cred
        widget: cy_cred
        widget_config:
          display_keys: false
          cred_types:
            - azure
        type: string
        default: "((azure))"
        required: true
    - name: Azure Infrastructure
      technologies: [terraform]
      vars:
      - name: "Azure location"
        description: "Azure location for Terraform."
        key: azure_location
        widget: auto_complete
        type: string
        values:
            - Australia Central
            - China East
            - China North
            - East Asia
            - East US
            - France Central
            - France South
            - North Europe
            - Southeast Asia
            - South Africa North
            - South Africa West
            - West Europe
            - West US
        default: "West Europe"
        required: true
      - name: "Existing resource group name"
        description: "The name of the existing resource group where the resources will be deployed."
        key: rg_name
        widget: simple_text
        type: string
        default: ""
        required: true
{%- elif stack_usecase == "gcp" %}
  - name: GCP Cloud Provider
    groups:
    - name: Access Configuration
      technologies: [pipeline]
      vars:
      - name: "GCP credentials"
        description: "Google Cloud Platform JSON credentials to use for Terraform."
        key: gcp_credentials_json
        widget: cy_cred
        widget_config:
          display_keys: false
          cred_types:
            - gcp
        type: string
        default: "((gcp))"
        required: true
      - name: "GCP project"
        description: "Google Cloud Platform project ID for Terraform."
        key: gcp_project
        widget: simple_text
        type: string
        default: ""
        required: true
      - name: "GCP zone"
        description: "Google Cloud Platform zone to use for Terraform."
        key: gcp_zone
        widget: dropdown
        type: map
        default: "europe-west1-b"
        values:
          - { "value": "asia-east1-a", "label": "asia-east1-a: Changhua County, Taiwan, APAC" }
          - { "value": "asia-east1-b", "label": "asia-east1-b: Changhua County, Taiwan, APAC" }
          - { "value": "asia-east1-c", "label": "Changhua County, Taiwan, APAC" }
          - { "value": "asia-east2-a", "label": "Hong Kong, APAC" }
          - { "value": "asia-east2-b", "label": "Hong Kong, APAC" }
          - { "value": "asia-east2-c", "label": "Hong Kong, APAC" }
          - { "value": "asia-northeast1-a", "label": "Tokyo, Japan, APAC" }
          - { "value": "asia-northeast1-b", "label": "Tokyo, Japan, APAC" }
          - { "value": "asia-northeast1-c", "label": "Tokyo, Japan, APAC" }
          - { "value": "asia-northeast2-a", "label": "Osaka, Japan, APAC" }
          - { "value": "asia-northeast2-b", "label": "Osaka, Japan, APAC" }
          - { "value": "asia-northeast2-c", "label": "Osaka, Japan, APAC" }
          - { "value": "asia-northeast3-a", "label": "Seoul, South Korea, APAC" }
          - { "value": "asia-northeast3-b", "label": "Seoul, South Korea, APAC" }
          - { "value": "asia-northeast3-c", "label": "Seoul, South Korea, APAC" }
          - { "value": "asia-south1-a", "label": "Mumbai, India APAC" }
          - { "value": "asia-south1-b", "label": "Mumbai, India APAC" }
          - { "value": "asia-south1-c", "label": "Mumbai, India APAC" }
          - { "value": "asia-south2-a", "label": "Delhi, India APAC" }
          - { "value": "asia-south2-b", "label": "Delhi, India APAC" }
          - { "value": "asia-south2-c", "label": "Delhi, India APAC" }
          - { "value": "asia-southeast1-a", "label": "Jurong West, Singapore, APAC" }
          - { "value": "asia-southeast1-b", "label": "Jurong West, Singapore, APAC" }
          - { "value": "asia-southeast1-c", "label": "Jurong West, Singapore, APAC" }
          - { "value": "asia-southeast2-a", "label": "Jakarta, Indonesia, APAC" }
          - { "value": "asia-southeast2-b", "label": "Jakarta, Indonesia, APAC" }
          - { "value": "asia-southeast2-c", "label": "Jakarta, Indonesia, APAC" }
          - { "value": "australia-southeast1-a", "label": "Sydney, Australia, APAC" }
          - { "value": "australia-southeast1-b", "label": "Sydney, Australia, APAC" }
          - { "value": "australia-southeast1-c", "label": "Sydney, Australia, APAC" }
          - { "value": "australia-southeast2-a", "label": "Melbourne, Australia, APAC" }
          - { "value": "australia-southeast2-b", "label": "Melbourne, Australia, APAC" }
          - { "value": "australia-southeast2-c", "label": "Melbourne, Australia, APAC" }
          - { "value": "europe-central2-a", "label": "Warsaw, Poland, Europe" }
          - { "value": "europe-central2-b", "label": "Warsaw, Poland, Europe" }
          - { "value": "europe-central2-c", "label": "Warsaw, Poland, Europe" }
          - { "value": "europe-north1-a", "label": "Hamina, Finland, Europe" }
          - { "value": "europe-north1-b", "label": "Hamina, Finland, Europe" }
          - { "value": "europe-north1-c", "label": "Hamina, Finland, Europe" }
          - { "value": "europe-west1-b", "label": "St. Ghislain, Belgium, Europe" }
          - { "value": "europe-west1-c", "label": "St. Ghislain, Belgium, Europe" }
          - { "value": "europe-west1-d", "label": "St. Ghislain, Belgium, Europe" }
          - { "value": "europe-west2-a", "label": "London, England, Europe" }
          - { "value": "europe-west2-b", "label": "London, England, Europe" }
          - { "value": "europe-west2-c", "label": "London, England, Europe" }
          - { "value": "europe-west3-a", "label": "Frankfurt, Germany Europe" }
          - { "value": "europe-west3-b", "label": "Frankfurt, Germany Europe" }
          - { "value": "europe-west3-c", "label": "Frankfurt, Germany Europe" }
          - { "value": "europe-west4-a", "label": "Eemshaven, Netherlands, Europe" }
          - { "value": "europe-west4-b", "label": "Eemshaven, Netherlands, Europe" }
          - { "value": "europe-west4-c", "label": "Eemshaven, Netherlands, Europe" }
          - { "value": "europe-west6-a", "label": "Zurich, Switzerland, Europe" }
          - { "value": "europe-west6-b", "label": "Zurich, Switzerland, Europe" }
          - { "value": "europe-west6-c", "label": "Zurich, Switzerland, Europe" }
          - { "value": "northamerica-northeast1-a", "label": "Montréal, Québec, North America" }
          - { "value": "northamerica-northeast1-b", "label": "Montréal, Québec, North America" }
          - { "value": "northamerica-northeast1-c", "label": "Montréal, Québec, North America" }
          - { "value": "southamerica-east1-a", "label": "Osasco, São Paulo, Brazil, South America" }
          - { "value": "southamerica-east1-b", "label": "Osasco, São Paulo, Brazil, South America" }
          - { "value": "southamerica-east1-c", "label": "Osasco, São Paulo, Brazil, South America" }
          - { "value": "us-central1-a", "label": "Council Bluffs, Iowa, North America" }
          - { "value": "us-central1-b", "label": "Council Bluffs, Iowa, North America" }
          - { "value": "us-central1-c", "label": "Council Bluffs, Iowa, North America" }
          - { "value": "us-central1-f", "label": "Council Bluffs, Iowa, North America" }
          - { "value": "us-east1-b", "label": "Moncks Corner, South Carolina, North America" }
          - { "value": "us-east1-c", "label": "Moncks Corner, South Carolina, North America" }
          - { "value": "us-east1-d", "label": "Moncks Corner, South Carolina, North America" }
          - { "value": "us-east4-a", "label": "Ashburn, Virginia, North America" }
          - { "value": "us-east4-b", "label": "Ashburn, Virginia, North America" }
          - { "value": "us-east4-c", "label": "Ashburn, Virginia, North America" }
          - { "value": "us-west1-a", "label": "The Dalles, Oregon, North America" }
          - { "value": "us-west1-b", "label": "The Dalles, Oregon, North America" }
          - { "value": "us-west1-c", "label": "The Dalles, Oregon, North America" }
          - { "value": "us-west2-a", "label": "Los Angeles, California, North America" }
          - { "value": "us-west2-b", "label": "Los Angeles, California, North America" }
          - { "value": "us-west2-c", "label": "Los Angeles, California, North America" }
          - { "value": "us-west3-a", "label": "Salt Lake City, Utah, North America" }
          - { "value": "us-west3-b", "label": "Salt Lake City, Utah, North America" }
          - { "value": "us-west3-c", "label": "Salt Lake City, Utah, North America" }
          - { "value": "us-west4-a", "label": "Las Vegas, Nevada, North America" }
          - { "value": "us-west4-b", "label": "Las Vegas, Nevada, North America" }
          - { "value": "us-west4-c", "label": "Las Vegas, Nevada, North America" }
        required: true
{%- endif %}