---
# Configuration of the Cycloid stack
version: '2'
name: 'Helm template'
canonical: 'template-helm-nexus'
description: Deploys a Nexus Repository on a Kubernetes cluster using Helm.
author: '{{ stack_author }}'
image: 'https://cycloid-demo-stacks-logo.s3.eu-west-1.amazonaws.com/helm.svg'
status: 'public'
template: true
keywords:
- helm
- nexus
- provider:kubernetes
technologies:
- technology: helm

config:
  default:
    name: 'Kubernetes'
    description: 'Deploys a Nexus Repository in a Kubernetes cluster'
    cloud_provider: kubernetes
    # Pipeline and variable configuration for the GCP CD pipeline use case
    pipeline:
      pipeline:
        path: 'pipeline/pipeline.yml'
      variables:
        path: 'pipeline/variables.sample.yml'
        destination: '($ project $)/pipeline/($ environment $)/variables.yml'
    # Configuration of terraform
    terraform:
      main:
        path: 'terraform/main.tf'
        destination: '($ project $)/kubernetes/($ environment $)/main.tf'