---
# Configuration of the Cycloid stack
version: '2'
name: 'Ansible Template'
canonical: 'template-ansible'
description: Supports bulk operations such as rebooting VMs, restarting services, installing packages or creating users on a set of targeted virtual machines using Ansible.
author: '{{ stack_author }}'
image: 'https://cycloid-demo-stacks-logo.s3.eu-west-1.amazonaws.com/ansible.png'
status: 'public'
template: true
keywords:
- ansible
- '{{ stack_usecase }}'
technologies:
- technology: ansible
  version: 2.9

config:
  aws:
    name: 'AWS'
    description: 'Hosts are targeted with AWS Dynamic Inventory via resource tagging.'
    cloud_provider: aws
    # Pipeline and variable configuration for the AWS CD pipeline use case
    pipeline:
      pipeline:
        path: 'pipeline/pipeline.yml'
      variables:
        path: 'pipeline/variables.sample.yml'
        destination: '($ project $)/pipeline/($ environment $)/variables.yml'
    # Configuration of ansible for provisionning
    ansible:
      default:
        path: 'ansible/environments/operations.yml.sample'
        destination: '($ project $)/ansible/environments/($ environment $)-operations.yml'

  azure:
    name: 'Azure'
    description: 'Hosts are targeted with Azure Dynamic Inventory via resource tagging.'
    cloud_provider: azurerm
    # Pipeline and variable configuration for the Azure CD pipeline use case
    pipeline:
      pipeline:
        path: 'pipeline/pipeline.yml'
      variables:
        path: 'pipeline/variables.sample.yml'
        destination: '($ project $)/pipeline/($ environment $)/variables.yml'
    # Configuration of ansible for provisionning
    ansible:
      default:
        path: 'ansible/environments/operations.yml.sample'
        destination: '($ project $)/ansible/environments/($ environment $)-operations.yml'

  gcp:
    name: 'GCP'
    description: 'Hosts are targeted with GCP Dynamic Inventory via resource tagging.'
    cloud_provider: gcp
    # Pipeline and variable configuration for the GCP CD pipeline use case
    pipeline:
      pipeline:
        path: 'pipeline/pipeline.yml'
      variables:
        path: 'pipeline/variables.sample.yml'
        destination: '($ project $)/pipeline/($ environment $)/variables.yml'
    # Configuration of ansible for provisionning
    ansible:
      default:
        path: 'ansible/environments/operations.yml.sample'
        destination: '($ project $)/ansible/environments/($ environment $)-operations.yml'

  manual:
    name: manual
    description: 'Hosts are targeted with a static list of FQDN or IP addresses.'
    # Pipeline and variable configuration
    pipeline:
      pipeline:
        path: 'pipeline/pipeline.yml'
      variables:
        path: 'pipeline/variables.sample.yml'
        destination: '($ project $)/pipeline/($ environment $)/variables.yml'
    # Configuration of ansible for provisionning
    ansible:
      default:
        path: 'ansible/environments/operations.yml.sample'
        destination: '($ project $)/ansible/environments/($ environment $)-operations.yml'
